config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
                  path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
                  path(
                      "about/",
                      TemplateView.as_view(template_name="pages/about.html"),
                      name="about",
                  ),
                  # Django Admin, use {% url 'admin:index' %}
                  path(settings.ADMIN_URL, admin.site.urls),

                  # User management
                  path(
                      "users/",
                      include("miseq_portal.users.urls", namespace="users"),
                  ),
                  path("accounts/", include("allauth.urls")),

                  # Your stuff: custom urls includes go here
                  path("miseq_viewer/", include("miseq_portal.miseq_viewer.urls")),
                  path("miseq_uploader/", include("miseq_portal.miseq_uploader.urls")),
                  path("sample_search/", include("miseq_portal.sample_search.urls")),
                  path("analysis/", include("miseq_portal.analysis.urls")),
                  path("sample_merge/", include("miseq_portal.sample_merge.urls")),
                  path("sample_workbooks/", include("miseq_portal.sample_workbooks.urls")),
                  path("sample_downloader/", include("miseq_portal.sample_downloader.urls")),
                  path("minion_viewer/", include("miseq_portal.minion_viewer.urls")),
                  path("minion_uploader/", include("miseq_portal.minion_uploader.urls")),
              ] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

miseq_portal/analysis/urls.py
from django.urls import path, re_path

from miseq_portal.analysis.views import (
    tool_selection_view,
    my_jobs_view,
    job_submitted_view,
    analysis_group_detail_view,
    analysis_group_delete_view,
    analysis_group_delete_success_view,
    sample_select_view
)

app_name = "analysis"
urlpatterns = [
    # Sample selector
    path("sample_select/", view=sample_select_view, name="sample_select"),

    # Page for selecting analysis tools
    path("sample_select/tools/", view=tool_selection_view, name="tool_selection"),

    # Successful job submission page
    path("sample_select/tools/job_submitted/", view=job_submitted_view, name="job_submitted"),

    # Analysis jobs pages
    path("my_jobs/", view=my_jobs_view, name="my_jobs"),
    re_path("^my_jobs/(?P<pk>\d+)$", view=analysis_group_detail_view, name="analysis_group_detail_view"),
    re_path("^my_jobs/(?P<pk>\d+)/delete$", view=analysis_group_delete_view, name="analysis_group_delete_view"),

    # Analysis deleted success page
    path("analysis_group_deleted/success", view=analysis_group_delete_success_view,
         name="analysis_group_delete_success_view")
]

miseq_portal/core/urls.py
app_name = "core"

miseq_portal/minion_viewer/urls.py
from django.urls import path, re_path, include
from rest_framework import routers

from miseq_portal.minion_viewer.views import (
    minion_viewer_index_view,
    minion_run_list_view,
    minion_sample_detail_view,
    minion_run_detail_view,
    MinIONRunViewSet,
    MinIONRunSamplesheetViewSet,
    MinIONSampleViewSet,
)

app_name = "minion_viewer"

# Django-rest-framework (https://django-rest-framework-datatables.readthedocs.io/en/latest/tutorial.html)
router = routers.DefaultRouter()
router.register(r'minion_runs', MinIONRunViewSet, basename='minion-run')
router.register(r'minion_samples', MinIONSampleViewSet, basename='minion-sample')
router.register(r'minion_samplesheets', MinIONRunSamplesheetViewSet, basename='minion-samplesheet')

urlpatterns = [
    path("", view=minion_viewer_index_view, name="minion_viewer_index"),
    re_path("^api/", include(router.urls), name="minion_viewer_api"),
    path("runs/", view=minion_run_list_view, name="minion_viewer_runs"),
    re_path("^run/(?P<pk>\d+)$", view=minion_run_detail_view, name="minion_run_detail"),
    re_path("^sample/(?P<pk>\d+)$", view=minion_sample_detail_view,
            name="minion_sample_detail")
]

miseq_portal/miseq_viewer/urls.py
from django.urls import path, re_path, include
from rest_framework import routers

from miseq_portal.miseq_viewer.views import (
    project_list_view,
    project_detail_view,
    run_list_view,
    run_detail_view,
    sample_detail_view,
    qaqc_excel,
    SampleViewSet, RunViewSet, ProjectViewSet
    # samples_api_view
)

app_name = "miseq_viewer"

# Django-rest-framework (https://django-rest-framework-datatables.readthedocs.io/en/latest/tutorial.html)
router = routers.DefaultRouter()
router.register(r'samples', SampleViewSet, basename='samples-detail')
router.register(r'runs', RunViewSet, basename='runs-detail')
router.register(r'projects', ProjectViewSet, basename='projects-detail')

urlpatterns = [
    path("projects/", view=project_list_view, name="miseq_viewer_projects"),
    path("runs/", view=run_list_view, name="miseq_viewer_runs"),
    path('qaqcexcel/', view=qaqc_excel, name='miseq_viewer_qaqc_excel'),
    # path("samples_api/", view=samples_api_view, name="miseq_viewer_samples_api"),
    re_path("^api/", include(router.urls), name="miseq_viewer_api"),
    re_path("^project/(?P<pk>\d+)$", view=project_detail_view, name="miseq_viewer_project_detail"),
    re_path("^run/(?P<pk>\d+)$", view=run_detail_view, name="miseq_viewer_run_detail"),
    re_path("^sample/(?P<pk>\d+)$", view=sample_detail_view,
            name="miseq_viewer_sample_detail")
]

miseq_portal/users/urls.py
from django.urls import path

from miseq_portal.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

miseq_portal/minion_uploader/models.py
from django.db import models

# Create your models here.

miseq_portal/analysis/views.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import View, TemplateView, DetailView, DeleteView

from miseq_portal.analysis.forms import AnalysisToolForm
from miseq_portal.analysis.models import AnalysisSample, AnalysisGroup, SendsketchResult, MobSuiteAnalysisPlasmid, \
    MobSuiteAnalysisGroup, RGIResult, RGIGroupResult, ConfindrGroupResult, ConfindrResult, rMLSTResult
from miseq_portal.analysis.tasks import submit_analysis_job
from miseq_portal.miseq_viewer.models import Sample, UserProjectRelationship

logger = logging.getLogger('django')


class SampleSelectView(LoginRequiredMixin, TemplateView):
    template_name = "analysis/sample_select.html"
    success_url = 'tools/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['approved_users'] = UserProjectRelationship.objects.filter(user_id=self.request.user)
        return context

    def post(self, request, *args, **kwargs):
        # Grab sample list from user selection from the analysis_index.html page via AJAX
        sample_id_list = request.POST.getlist('sample_id_list[]')

        # Get corresponding Sample objects from user selection
        sample_object_list = list()
        for sample_id in sample_id_list:
            sample_object = Sample.objects.get(sample_id=sample_id)
            sample_object_list.append(sample_object)

        # Create new AnalysisGroup
        analysis_group = AnalysisGroup(user=request.user)
        analysis_group.save()

        # Add objects to SampleAnalysisTemporaryGroup table
        for sample_object in sample_object_list:
            obj = AnalysisSample(sample_id=sample_object, user=request.user, group_id=analysis_group)
            obj.save()
        logger.info(f'Saved {sample_object_list} to {analysis_group} for user "{request.user}"')

        context = {'success': True,
                   'url': self.success_url}
        return JsonResponse(context)


sample_select_view = SampleSelectView.as_view()


class ToolSelectionView(LoginRequiredMixin, View):
    template_name = 'analysis/tool_selection.html'
    model = AnalysisGroup
    form_class = AnalysisToolForm
    success_url = 'job_submitted/'

    def get(self, request, *args, **kwargs):
        # Get the most recent Analysis Group belonging to user
        analysis_group = AnalysisGroup.objects.filter(user_id=self.request.user).order_by('-id')[0]
        analysis_samples = AnalysisSample.objects.filter(group_id=analysis_group)

        context = {
            'analysis_group': analysis_group,
            'analysis_samples': analysis_samples,
            'form': self.form_class
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            logger.info("Valid form")

            # Set job type for analysis_group
            analysis_group = AnalysisGroup.objects.filter(user_id=self.request.user).order_by('-id')[0]
            analysis_group.job_type = form.cleaned_data['job_type']
            analysis_group.save()
            logger.info(f"Queued job for {analysis_group}")

            # Submit analysis to queue. Note that the ID must be submitted because a straight object is not serializable
            submit_analysis_job.apply_async(args=[],
                                            kwargs={'analysis_group': analysis_group.id},
                                            queue='analysis_queue')
            return redirect(self.success_url)
        else:
            logger.error("Form is not valid")
            return render(request, self.template_name, {'form': form})


tool_selection_view = ToolSelectionView.as_view()


class MyJobsView(LoginRequiredMixin, View):
    template_name = 'analysis/my_jobs.html'

    def get(self, request):
        # Display samples only belonging only to the requesting user
        analysis_group = AnalysisGroup.objects.filter(user_id=self.request.user)
        context = {
            'analysis_group': analysis_group
        }
        return render(request, self.template_name, context)


my_jobs_view = MyJobsView.as_view()


class AnalysisGroupDetailView(LoginRequiredMixin, DetailView):
    model = AnalysisGroup
    context_object_name = 'analysis_group'
    template_name = "analysis/analysis_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['analysis_samples'] = AnalysisSample.objects.filter(group_id=context['analysis_group'])

        # Sendketch
        if context['analysis_group'].job_type == 'SendSketch':
            context['sendsketch_results'] = SendsketchResult.objects.filter(
                sample_id__analysissample__group_id=context['analysis_group']).order_by('-sample_id')

        # Mob Suite
        elif context['analysis_group'].job_type == 'MobRecon':

            # Add analysis samples to context
            context['mob_suite_analysis_samples'] = MobSuiteAnalysisGroup.objects.filter(
                analysis_sample__group_id=context['analysis_group']).order_by('-analysis_sample__sample_id')

            # Add plasmids to context
            context['mob_suite_analysis_plasmids'] = MobSuiteAnalysisPlasmid.objects.filter(
                group_id__analysis_sample__group_id=context['analysis_group']).order_by('-sample_id')

        # RGI
        elif context['analysis_group'].job_type == 'RGI':

            # RGI Result
            context['rgi_results'] = RGIResult.objects.filter(
                analysis_sample__group_id=context['analysis_group']).order_by('-analysis_sample__sample_id')

            # Group Result
            try:
                context['rgi_group_result'] = RGIGroupResult.objects.get(analysis_group=context['analysis_group'])
            except Exception as e:
                logger.info(f'Could not find group result for analysis; probably only executed on 1 sample')
                logger.info(e)
                context['rgi_group_result'] = None

        # Confindr
        elif context['analysis_group'].job_type == 'Confindr':
            context['confindr_group_result'] = ConfindrGroupResult.objects.get(analysis_group=context['analysis_group'])
            context['confindr_results'] = ConfindrResult.objects.filter(
                analysis_sample__group_id=context['analysis_group']).order_by('-analysis_sample__sample_id')
        # rMLST
        elif context['analysis_group'].job_type == 'rMLST':
            context['rmlst_results'] = rMLSTResult.objects.filter(
                analysis_sample__group_id=context['analysis_group']).order_by('-analysis_sample__sample_id')

        else:
            return context
        return context


analysis_group_detail_view = AnalysisGroupDetailView.as_view()


class JobSubmittedView(LoginRequiredMixin, TemplateView):
    template_name = 'analysis/job_submitted.html'


job_submitted_view = JobSubmittedView.as_view()


class AnalysisGroupDeleteView(LoginRequiredMixin, DeleteView):
    model = AnalysisGroup
    success_url = reverse_lazy('analysis:analysis_group_delete_success_view')


analysis_group_delete_view = AnalysisGroupDeleteView.as_view()


class AnalysisGroupDeleteSuccessView(LoginRequiredMixin, TemplateView):
    template_name = 'analysis/analysisgroup_delete_success.html'


analysis_group_delete_success_view = AnalysisGroupDeleteSuccessView.as_view()

miseq_portal/minion_viewer/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


# Create your views here.
class MinIONViewerIndexView(LoginRequiredMixin, TemplateView):
    template_name = 'minion_viewer/minion_viewer_index.html'

    def get_context_data(self, **kwargs):
        context = super(MinIONViewerIndexView, self).get_context_data(**kwargs)
        return context


minion_viewer_index_view = MinIONViewerIndexView.as_view()

miseq_portal/miseq_uploader/views.py
import logging
from pathlib import Path

from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views.generic import View, TemplateView

from miseq_portal.miseq_uploader.forms import UploadMiSeqDirectoryForm
from miseq_portal.miseq_uploader.upload_to_db import receive_miseq_run_dir

# logger = logging.getLogger('raven')
logger = logging.getLogger('django')


@method_decorator(staff_member_required, name='dispatch')
class MiseqUploaderView(LoginRequiredMixin, TemplateView):
    template_name = 'miseq_uploader/miseq_uploader.html'


miseq_uploader_view = MiseqUploaderView.as_view()


@method_decorator(staff_member_required, name='dispatch')
class SampleFormView(LoginRequiredMixin, View):
    template_name = 'miseq_uploader/sample_uploader.html'

    def get(self, request):
        return render(request, self.template_name, {})


sample_form_view = SampleFormView.as_view()


@method_decorator(staff_member_required, name='dispatch')
class MiSeqFormView(LoginRequiredMixin, UserPassesTestMixin, View):
    form_class = UploadMiSeqDirectoryForm
    template_name = 'miseq_uploader/upload_miseq_directory.html'

    # success_url = 'miseq_directory_uploaded/'  # TODO: actually make this page
    success_url = 'run_submitted/'

    # Only staff can access this page
    def test_func(self):
        if self.request.user.is_staff:
            return True
        else:
            raise Http404("You are not authenticated to view this page.")

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)

        if form.is_valid():
            receive_miseq_run_dir(Path(request.POST['miseq_directory']))
            return redirect(self.success_url)
        else:
            logging.warning("Could not submit form!")
            return render(request, self.template_name, {'form': form})


miseq_form_view = MiSeqFormView.as_view()


@method_decorator(staff_member_required, name='dispatch')
class RunSubmittedView(LoginRequiredMixin, TemplateView):
    template_name = 'miseq_uploader/run_submitted.html'


run_submitted_view = RunSubmittedView.as_view()

miseq_portal/templates/miseq_viewer/project_detail.html
{% extends "base.html" %}
{% load static i18n %}
{% block extra_css %}
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.jqueryui.min.css">
{% endblock %}
{% block title %}{{ project }}{% endblock %}

{% block content %}
  <div class="row">
    <div class="col">
      <h1><strong>Project: </strong>{{ project }}</h1>
    </div>
    <div class="col">
      <h5><strong>Owner: </strong>{{ project.project_owner }}</h5>
      <h5><strong>Created: </strong>{{ project.created }}</h5>
    </div>
  </div>

  <h4>MiSeq Samples</h4>
    <form method="post" action="{% url 'miseq_viewer:miseq_viewer_qaqc_excel' %}">
      {% csrf_token %}
      <input type="hidden" name="sample_list" value="{% for sample in sample_list %}{{ sample.id }},{% endfor %}">
      <button type="submit" class="btn btn-primary"><i
        class="fas fa-download"></i> Download QA/QC Results</button>
    </form>
  <br>
  <table id="sample-table" class="display" style="width:100%">
    <thead>
    <tr>
      <th>Sample ID</th>
      <th>Sample Name</th>
      <th>Run ID</th>
      <th>Yield (Mbp)</th>
      <th>Top RefSeq Hit</th>
      <th>Date Created</th>
    </tr>
    </thead>
    <tbody>
    {% for sample in sample_list %}
      <tr>
        <td>
          <a href="{% url 'miseq_viewer:miseq_viewer_sample_detail' pk=sample.pk %}">
              {{ sample.sample_id }}
          </a>
        </td>
        <td>
            {{ sample.sample_name }}
        </td>
        <td>
            {% if sample.run_id != None %}
              <a href="{% url 'miseq_viewer:miseq_viewer_run_detail' pk=sample.run_id.pk %}">
                  {{ sample.run_id }}
              </a>
            {% else %}
              N/A
            {% endif %}
        </td>
        <td>
            {% if sample in has_sample_log_data %}
                {{ sample.samplelogdata.sample_yield_mbp | floatformat:2 }}
            {% endif %}
        </td>
        <td>
            {% if has_mash_result %}
                {{ sample.mashresult.top_hit }}
            {% endif %}
        </td>
        <td>
            {{ sample.created }}
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

    {% if minion_sample_list|length > 0 %}
      <br>
      <h4>MinION Samples</h4>
      <table id="minion-sample-table" class="display" style="width:100%">
        <thead>
        <tr>
          <th>Sample ID</th>
          <th>Sample Name</th>
          <th>Run ID</th>
          <th>Date Created</th>
        </tr>
        </thead>
        <tbody>
        {% for sample in minion_sample_list %}
          <tr>
            <td><a href="{% url 'minion_viewer:minion_sample_detail' pk=sample.pk %}">
                {{ sample.sample_id }}
            </a></td>
            <td>{{ sample.sample_name }}</td>
            <td><a href="{% url 'minion_viewer:minion_run_detail' pk=sample.run_id.pk %}">
                {{ sample.run_id }}
            </a></td>
            <td>{{ sample.created }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    {% endif %}

{% endblock content %}


{% block extra_javascript %}
  <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/dataTables.jqueryui.min.js"></script>
  <script>
      $(document).ready(function () {
          $('#sample-table').DataTable();
          $('#minion-sample-table').DataTable();
      });
  </script>
{% endblock %}

miseq_portal/templates/miseq_viewer/project_list.html
{% extends "base.html" %}
{% load static i18n %}
{% load miseq_viewer_extras %}
{% block extra_css %}
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.jqueryui.min.css">
{% endblock %}

{% block title %}Projects{% endblock %}

{% block content %}
  <div class="container-fluid">

    <div class="page-header">
      <h1>Projects</h1>
    </div>

    <div class="alert alert-info" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h5><i class="fas fa-sticky-note"></i> Note</h5>
      This page displays all <strong>Projects</strong> your user account has been associated with.
      If you believe you are missing any projects from the following list, please send an email to <strong>julie.shay@canada.ca</strong>
      to request access.
    </div>

    <div class="list-group">
      <table id="project_table" class="display">
        <thead>
        <tr>
          <th>Project ID</th>
          <th># Samples</th>
          <th>Date Created</th>
          <th>Last Updated</th>
        </tr>
        </thead>
        <tbody>
        {% for project in project_list %}
          <tr>
            <td>
              <a href="{% url 'miseq_viewer:miseq_viewer_project_detail' project.pk %}">
                {{ project.project_id }}
              </a>
            </td>
            <td>
              {{ sample_count_dict|get_item:project.project_id }}
            </td>
            <td data-order="{{ project.created|date:"Y-m-d H:i" }}">
              {{ project.created|date:"d N Y" }}
            </td>
            <td data-order="{{ project.last_updated|date:"Y-m-d H:i" }}">
              {{ project.last_updated|date:"d N Y" }}
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
      <br>
    </div>
    <br>
    {% include "miseq_viewer/overview_chart.html" %}
    <br>
  </div>

{% endblock content %}

{% block extra_javascript %}
  <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/dataTables.jqueryui.min.js"></script>
  <script>
    $(document).ready(function () {
      $('#project_table').DataTable({
        "pageLength": 50,
        "order":[[3,"desc"]]
      });
    });
  </script>
{% endblock %}

miseq_portal/templates/miseq_viewer/run_detail.html
{% extends "base.html" %}
{% load static i18n %}
{% load miseq_viewer_extras %}
{% block extra_css %}
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.jqueryui.min.css">
{% endblock %}
{% block title %}{{ run.run_id }}{% endblock %}

{% block content %}
  <div class="container-fluid">

    <div class="page-header">
      <h1>{{ run }}</h1>
      <form method="post" action="{% url 'miseq_viewer:miseq_viewer_qaqc_excel' %}">
        {% csrf_token %}
        <a class="btn btn-primary" href="{{ run.sample_sheet.url }}" role="button"><i
          class="fas fa-download"></i> Download SampleSheet.csv
        </a>
        <input type="hidden" name="sample_list" value="{% for sample in sample_list %}{{ sample.id }},{% endfor %}">
        <button type="submit" class="btn btn-primary"><i
              class="fas fa-download"></i> Download QA/QC Results</button>
      </form>
    </div>

    <hr>

    <div class="container">
      {% if interop_data_avaiable %}
        <div id="interop-charts">
          {% include "miseq_viewer/qscore_chart.html" %}
        </div>
      {% else %}
        <div class="alert alert-warning" role="alert">
          Could not retrieve InterOp data for {{ run.run_id }}
        </div>
      {% endif %}
    </div>

    <table id="samplesheet-header-table" class="table table-striped table-sm table-compact">
      <thead>
      <tr>
        <th>Header</th>
        <th>Value</th>
      </tr>
      </thead>
      <tbody>
      {% for field, value in samplesheet_headers.get_fields %}
        {% if field != 'created' and field != 'modified' and value != "" %}
          <tr>
            <td>{{ field|parse_samplesheet_header_value }}</td>
            <td>{{ value }}</td>
          </tr>
        {% endif %}
      {% endfor %}
      </tbody>
    </table>

    <h4>Run Samples</h4>
    <table id="run-table" class="display" style="width:100%">
      <thead>
      <tr>
        <th>Sample ID</th>
        <th>Sample Name</th>
        <th>Description</th>
        <th>Top RefSeq</th>
      </tr>
      </thead>
      <tbody>
      {% for sample in sample_list %}
        <tr>
          <td>
            <a href="{% url 'miseq_viewer:miseq_viewer_sample_detail' pk=sample.pk %}">
              {{ sample.sample_id }}
            </a>
          </td>
          <td>
            {{ sample.sample_name }}
          </td>
          <td>
            {{ sample.samplesheetsampledata.description }}
          </td>
          <td>
            {{ sample.mashresult.top_hit }}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>

    <br>
  </div>
{% endblock content %}


{% block extra_javascript %}
  <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/dataTables.jqueryui.min.js"></script>
  <script>
    $(document).ready(function () {
      $('#run-table').DataTable({
        "scrollX": true,
        "pageLength": 100
      })
    })
  </script>
{% endblock %}

miseq_portal/templates/miseq_viewer/sample_download.html
{% extends "base.html" %}
{% load static i18n %}
{% block extra_css %}

{% endblock %}

{% block title %}{{ sample }}{% endblock %}

{% block content %}

{% endblock content %}

{% block extra_javascript %}

{% endblock %}