config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
                  path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
                  path(
                      "about/",
                      TemplateView.as_view(template_name="pages/about.html"),
                      name="about",
                  ),
                  # Django Admin, use {% url 'admin:index' %}
                  path(settings.ADMIN_URL, admin.site.urls),

                  # User management
                  path(
                      "users/",
                      include("miseq_portal.users.urls", namespace="users"),
                  ),
                  path("accounts/", include("allauth.urls")),

                  # Your stuff: custom urls includes go here
                  path("miseq_viewer/", include("miseq_portal.miseq_viewer.urls")),
                  path("miseq_uploader/", include("miseq_portal.miseq_uploader.urls")),
                  path("sample_search/", include("miseq_portal.sample_search.urls")),
                  path("analysis/", include("miseq_portal.analysis.urls")),
                  path("sample_merge/", include("miseq_portal.sample_merge.urls")),
                  path("sample_workbooks/", include("miseq_portal.sample_workbooks.urls")),
                  path("sample_downloader/", include("miseq_portal.sample_downloader.urls")),
                  path("minion_viewer/", include("miseq_portal.minion_viewer.urls")),
                  path("minion_uploader/", include("miseq_portal.minion_uploader.urls")),
              ] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

miseq_portal/analysis/urls.py
from django.urls import path, re_path

from miseq_portal.analysis.views import (
    tool_selection_view,
    my_jobs_view,
    job_submitted_view,
    analysis_group_detail_view,
    analysis_group_delete_view,
    analysis_group_delete_success_view,
    sample_select_view
)

app_name = "analysis"
urlpatterns = [
    # Sample selector
    path("sample_select/", view=sample_select_view, name="sample_select"),

    # Page for selecting analysis tools
    path("sample_select/tools/", view=tool_selection_view, name="tool_selection"),

    # Successful job submission page
    path("sample_select/tools/job_submitted/", view=job_submitted_view, name="job_submitted"),

    # Analysis jobs pages
    path("my_jobs/", view=my_jobs_view, name="my_jobs"),
    re_path("^my_jobs/(?P<pk>\d+)$", view=analysis_group_detail_view, name="analysis_group_detail_view"),
    re_path("^my_jobs/(?P<pk>\d+)/delete$", view=analysis_group_delete_view, name="analysis_group_delete_view"),

    # Analysis deleted success page
    path("analysis_group_deleted/success", view=analysis_group_delete_success_view,
         name="analysis_group_delete_success_view")
]

miseq_portal/core/urls.py
app_name = "core"

miseq_portal/sample_workbooks/urls.py
from django.urls import path, re_path, include
from rest_framework import routers

from miseq_portal.sample_workbooks.views import (
    sample_workbook_index_view,
    create_new_workbook_view,
    workbook_detail_view,
    workbook_delete_view,
    workbook_delete_success_view,
    WorkbookViewSet, WorkbookSampleViewset
)

app_name = "sample_workbooks"

# Django-rest-framework (https://django-rest-framework-datatables.readthedocs.io/en/latest/tutorial.html)
router = routers.DefaultRouter()
router.register(r'workbooks', WorkbookViewSet, basename='workbooks-detail')
router.register(r'workbooksamples', WorkbookSampleViewset, basename='workbook-samples-detail')

urlpatterns = [
    path("", view=sample_workbook_index_view, name="sample_workbook_index"),
    path("create/", view=create_new_workbook_view, name="create_new_workbook"),
    re_path("^detail/(?P<pk>\d+)$", view=workbook_detail_view, name="workbook_detail"),
    re_path("^api/", include(router.urls), name="workbook_api"),

    # Deleting Workbook views
    re_path("^detail/(?P<pk>\d+)/delete$", view=workbook_delete_view, name="workbook_delete_view"),
    re_path("^delete_success/$", view=workbook_delete_success_view, name="workbook_delete_success_view")
]

miseq_portal/users/urls.py
from django.urls import path

from miseq_portal.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

miseq_portal/analysis/forms.py
from django import forms
from .models import AnalysisGroup

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class AnalysisToolForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AnalysisToolForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-submitAnalysisJobForm'
        self.helper.form_class = 'blueForms'
        self.helper.form_method = 'post'
        self.helper.form_action = 'tool_selection'
        self.fields['job_type'].label = 'Job Type'
        self.helper.add_input(Submit('submit', 'Submit', css_class='btn btn-success'))

    class Meta:
        model = AnalysisGroup
        fields = ['job_type']
        widgets = {
            'job_type': forms.RadioSelect,
        }

miseq_portal/miseq_uploader/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.forms import Form


# MISEQ DIRECTORY
class UploadMiSeqDirectoryForm(Form):
    miseq_directory = forms.CharField(widget=forms.TextInput())

    def __init__(self, *args, **kwargs):
        super(UploadMiSeqDirectoryForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-uploadMiSeqDirectoryForm'
        self.helper.form_class = 'blueForms'
        self.helper.form_method = 'post'
        self.helper.form_action = 'upload_miseq_directory'
        self.fields['miseq_directory'].label = 'MiSeq Directory'
        self.helper.add_input(Submit('submit', 'Submit'))

miseq_portal/analysis/views.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import View, TemplateView, DetailView, DeleteView

from miseq_portal.analysis.forms import AnalysisToolForm
from miseq_portal.analysis.models import AnalysisSample, AnalysisGroup, SendsketchResult, MobSuiteAnalysisPlasmid, \
    MobSuiteAnalysisGroup, RGIResult, RGIGroupResult, ConfindrGroupResult, ConfindrResult, rMLSTResult
from miseq_portal.analysis.tasks import submit_analysis_job
from miseq_portal.miseq_viewer.models import Sample, UserProjectRelationship

logger = logging.getLogger('django')


class SampleSelectView(LoginRequiredMixin, TemplateView):
    template_name = "analysis/sample_select.html"
    success_url = 'tools/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['approved_users'] = UserProjectRelationship.objects.filter(user_id=self.request.user)
        return context

    def post(self, request, *args, **kwargs):
        # Grab sample list from user selection from the analysis_index.html page via AJAX
        sample_id_list = request.POST.getlist('sample_id_list[]')

        # Get corresponding Sample objects from user selection
        sample_object_list = list()
        for sample_id in sample_id_list:
            sample_object = Sample.objects.get(sample_id=sample_id)
            sample_object_list.append(sample_object)

        # Create new AnalysisGroup
        analysis_group = AnalysisGroup(user=request.user)
        analysis_group.save()

        # Add objects to SampleAnalysisTemporaryGroup table
        for sample_object in sample_object_list:
            obj = AnalysisSample(sample_id=sample_object, user=request.user, group_id=analysis_group)
            obj.save()
        logger.info(f'Saved {sample_object_list} to {analysis_group} for user "{request.user}"')

        context = {'success': True,
                   'url': self.success_url}
        return JsonResponse(context)


sample_select_view = SampleSelectView.as_view()


class ToolSelectionView(LoginRequiredMixin, View):
    template_name = 'analysis/tool_selection.html'
    model = AnalysisGroup
    form_class = AnalysisToolForm
    success_url = 'job_submitted/'

    def get(self, request, *args, **kwargs):
        # Get the most recent Analysis Group belonging to user
        analysis_group = AnalysisGroup.objects.filter(user_id=self.request.user).order_by('-id')[0]
        analysis_samples = AnalysisSample.objects.filter(group_id=analysis_group)

        context = {
            'analysis_group': analysis_group,
            'analysis_samples': analysis_samples,
            'form': self.form_class
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            logger.info("Valid form")

            # Set job type for analysis_group
            analysis_group = AnalysisGroup.objects.filter(user_id=self.request.user).order_by('-id')[0]
            analysis_group.job_type = form.cleaned_data['job_type']
            analysis_group.save()
            logger.info(f"Queued job for {analysis_group}")

            # Submit analysis to queue. Note that the ID must be submitted because a straight object is not serializable
            submit_analysis_job.apply_async(args=[],
                                            kwargs={'analysis_group': analysis_group.id},
                                            queue='analysis_queue')
            return redirect(self.success_url)
        else:
            logger.error("Form is not valid")
            return render(request, self.template_name, {'form': form})


tool_selection_view = ToolSelectionView.as_view()


class MyJobsView(LoginRequiredMixin, View):
    template_name = 'analysis/my_jobs.html'

    def get(self, request):
        # Display samples only belonging only to the requesting user
        analysis_group = AnalysisGroup.objects.filter(user_id=self.request.user)
        context = {
            'analysis_group': analysis_group
        }
        return render(request, self.template_name, context)


my_jobs_view = MyJobsView.as_view()


class AnalysisGroupDetailView(LoginRequiredMixin, DetailView):
    model = AnalysisGroup
    context_object_name = 'analysis_group'
    template_name = "analysis/analysis_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['analysis_samples'] = AnalysisSample.objects.filter(group_id=context['analysis_group'])

        # Sendketch
        if context['analysis_group'].job_type == 'SendSketch':
            context['sendsketch_results'] = SendsketchResult.objects.filter(
                sample_id__analysissample__group_id=context['analysis_group']).order_by('-sample_id')

        # Mob Suite
        elif context['analysis_group'].job_type == 'MobRecon':

            # Add analysis samples to context
            context['mob_suite_analysis_samples'] = MobSuiteAnalysisGroup.objects.filter(
                analysis_sample__group_id=context['analysis_group']).order_by('-analysis_sample__sample_id')

            # Add plasmids to context
            context['mob_suite_analysis_plasmids'] = MobSuiteAnalysisPlasmid.objects.filter(
                group_id__analysis_sample__group_id=context['analysis_group']).order_by('-sample_id')

        # RGI
        elif context['analysis_group'].job_type == 'RGI':

            # RGI Result
            context['rgi_results'] = RGIResult.objects.filter(
                analysis_sample__group_id=context['analysis_group']).order_by('-analysis_sample__sample_id')

            # Group Result
            try:
                context['rgi_group_result'] = RGIGroupResult.objects.get(analysis_group=context['analysis_group'])
            except Exception as e:
                logger.info(f'Could not find group result for analysis; probably only executed on 1 sample')
                logger.info(e)
                context['rgi_group_result'] = None

        # Confindr
        elif context['analysis_group'].job_type == 'Confindr':
            context['confindr_group_result'] = ConfindrGroupResult.objects.get(analysis_group=context['analysis_group'])
            context['confindr_results'] = ConfindrResult.objects.filter(
                analysis_sample__group_id=context['analysis_group']).order_by('-analysis_sample__sample_id')
        # rMLST
        elif context['analysis_group'].job_type == 'rMLST':
            context['rmlst_results'] = rMLSTResult.objects.filter(
                analysis_sample__group_id=context['analysis_group']).order_by('-analysis_sample__sample_id')

        else:
            return context
        return context


analysis_group_detail_view = AnalysisGroupDetailView.as_view()


class JobSubmittedView(LoginRequiredMixin, TemplateView):
    template_name = 'analysis/job_submitted.html'


job_submitted_view = JobSubmittedView.as_view()


class AnalysisGroupDeleteView(LoginRequiredMixin, DeleteView):
    model = AnalysisGroup
    success_url = reverse_lazy('analysis:analysis_group_delete_success_view')


analysis_group_delete_view = AnalysisGroupDeleteView.as_view()


class AnalysisGroupDeleteSuccessView(LoginRequiredMixin, TemplateView):
    template_name = 'analysis/analysisgroup_delete_success.html'


analysis_group_delete_success_view = AnalysisGroupDeleteSuccessView.as_view()

miseq_portal/minion_viewer/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


# Create your views here.
class MinIONViewerIndexView(LoginRequiredMixin, TemplateView):
    template_name = 'minion_viewer/minion_viewer_index.html'

    def get_context_data(self, **kwargs):
        context = super(MinIONViewerIndexView, self).get_context_data(**kwargs)
        return context


minion_viewer_index_view = MinIONViewerIndexView.as_view()

miseq_portal/miseq_uploader/views.py
import logging
from pathlib import Path

from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views.generic import View, TemplateView

from miseq_portal.miseq_uploader.forms import UploadMiSeqDirectoryForm
from miseq_portal.miseq_uploader.upload_to_db import receive_miseq_run_dir

# logger = logging.getLogger('raven')
logger = logging.getLogger('django')


@method_decorator(staff_member_required, name='dispatch')
class MiseqUploaderView(LoginRequiredMixin, TemplateView):
    template_name = 'miseq_uploader/miseq_uploader.html'


miseq_uploader_view = MiseqUploaderView.as_view()


@method_decorator(staff_member_required, name='dispatch')
class SampleFormView(LoginRequiredMixin, View):
    template_name = 'miseq_uploader/sample_uploader.html'

    def get(self, request):
        return render(request, self.template_name, {})


sample_form_view = SampleFormView.as_view()


@method_decorator(staff_member_required, name='dispatch')
class MiSeqFormView(LoginRequiredMixin, UserPassesTestMixin, View):
    form_class = UploadMiSeqDirectoryForm
    template_name = 'miseq_uploader/upload_miseq_directory.html'

    # success_url = 'miseq_directory_uploaded/'  # TODO: actually make this page
    success_url = 'run_submitted/'

    # Only staff can access this page
    def test_func(self):
        if self.request.user.is_staff:
            return True
        else:
            raise Http404("You are not authenticated to view this page.")

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)

        if form.is_valid():
            receive_miseq_run_dir(Path(request.POST['miseq_directory']))
            return redirect(self.success_url)
        else:
            logging.warning("Could not submit form!")
            return render(request, self.template_name, {'form': form})


miseq_form_view = MiSeqFormView.as_view()


@method_decorator(staff_member_required, name='dispatch')
class RunSubmittedView(LoginRequiredMixin, TemplateView):
    template_name = 'miseq_uploader/run_submitted.html'


run_submitted_view = RunSubmittedView.as_view()

miseq_portal/templates/sample_workbooks/create_new_workbook.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static i18n %}
{% block extra_css %}
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.jqueryui.min.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.dataTables.min.css">
{% endblock %}

{% block title %}Create{% endblock %}

{% block content %}

  <h1>Create New Workbook</h1>

  {# This form is rendered manually to accommodate passing the samples that the user selected to views.py #}
  {# https://simpleisbetterthancomplex.com/article/2017/08/19/how-to-render-django-form-manually.html #}
  <form method="post" class="uniForm">
    {% csrf_token %}

    {% for hidden_field in form.hidden_fields %}
      {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
      <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
          {{ error }}
        {% endfor %}
      </div>
    {% endif %}

    {% for field in form.visible_fields %}
      <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
          {% if field.errors %}
            {% render_field field class="form-control is-invalid" %}
            {% for error in field.errors %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
            {% render_field field class="form-control is-valid" %}
          {% endif %}
        {% else %}
          {% render_field field class="form-control" %}
        {% endif %}

        {% if field.help_text %}
          <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
      </div>
    {% endfor %}

    {# Sample Table - populated by django-rest-framework-datatables #}
    {# https://django-rest-framework-datatables.readthedocs.io/en/latest/ #}
    <label for="sample-table" class="col-form-label">Select Samples:</label>
    <table id="sample-table" class="display compact" style="width:100%" data-server-side="true"
           data-ajax="/miseq_viewer/api/samples/?format=datatables">
      <thead>
      <tr>
        <th data-data="sample_id">Sample ID</th>
        <th data-data="sample_name">Sample Name</th>
        <th data-data="project_id.project_id">Project ID</th>
        <th data-data="run_id.run_id">Run ID</th>
        <th data-data="mashresult.top_hit">Top RefSeq Hit</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      </tbody>
    </table>

    {#  This hidden input is updated on the fly according to samples selected in the above table. Passed to views.py #}
    <input type="hidden" id="sample_id_list" name="sample_id_list" value="">

    <button type="submit" class="btn btn-primary">Submit Workbook</button>
  </form>
  <br>

{% endblock %}

{% block extra_javascript %}
  <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/dataTables.jqueryui.min.js"></script>
  <script src="https://cdn.datatables.net/scroller/1.5.1/js/dataTables.scroller.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
  <script>
    $.ajaxSetup({
      headers: {"X-CSRFToken": '{{csrf_token}}'}
    });

    $(document).ready(function () {
      // Move the submit button below the sample selection table
      {#$("#submit-id-submit").detach().appendTo("#submit-button-container");#}

      let currently_selected_samples = [];

      let table = $('#sample-table').DataTable({
        dom: 'Blfrtips',
        processing: true,
        pageLength: 15,
        lengthMenu: [[15, 30, 45, 100], [15, 30, 45, 100]],
        columnDefs: [
          {
            "targets": '_all',
            "defaultContent": ""
          }
        ],
        buttons: [
          {
            text: 'Select All',
            action: function (e, dt, node, config) {
              // Apply the the selected status to all rows
              $('#sample-table tbody tr').removeClass("selected").toggleClass('selected');
              let selected_samples = table.rows('.selected').data();

              // Extract sample IDs and remove whitespace
              selected_samples = filter_sample_ids(selected_samples);

              // Update variable storing all currently selected samples with the new selection
              selected_samples.map(x => currently_selected_samples.push(x));
              $("#sample_id_list").val(currently_selected_samples);
            }
          },
          {
            text: 'Deselect All',
            action: function (e, dt, node, config) {
              // Remove selected status from all rows
              $('#sample-table tbody tr').removeClass("selected");

              // Grab currently displayed sample IDs
              let table_data = table.context[0].aoData;
              let currently_displayed_samples = [];
              for (var x = 0; x < table_data.length; x++) {
                currently_displayed_samples.push(table_data[x]._aData.sample_id)
              }
              $("#sample_id_list").val(currently_selected_samples);

              // Remove all rows currently displayed on the sample from currently_selected_samples
              remove_from_id_list(currently_displayed_samples);
            }
          }
        ],
      });

      // Clicking a row will toggle the selected class and update the currently_selected_samples list accordingly
      $('#sample-table tbody').on('click', 'tr', function () {
        // Toggle class
        let row = $(this).toggleClass('selected');

        // Determine if the row is selected or not and store bool in selected_status
        let classes = Array.from(row[0].classList);
        let selected_status = classes.includes('selected');

        // Extract sample_id
        let sample_id = row[0].cells[0].textContent;

        // If selected, add it to the currently_selected_samples array, otherwise remove it
        if (selected_status === true) {
          currently_selected_samples.push(sample_id)
        } else if (selected_status === false) {
          currently_selected_samples = currently_selected_samples.filter(x => x !== sample_id)
        }

        $("#sample_id_list").val(currently_selected_samples);

      });

      // Whenever the table is redrawn, update selected status to reflect previously selected samples
      $(document).on('draw.dt', function (e) {

        // Grab array of sample IDs that are currently displayed on the table
        let table_data = table.context[0].aoData;
        let currently_displayed_samples = [];
        for (var x = 0; x < table_data.length; x++) {
          currently_displayed_samples.push(table_data[x]._aData.sample_id)
        }

        // Get intersection between currently_selected_samples and currently_displayed_samples
        let samples_to_highlight = currently_selected_samples.filter(x => currently_displayed_samples.includes(x));

        // Iterate over table rows apply selected status if they are present in the currently_selected_samples array
        $('#sample-table tbody tr').each(function () {
          let current_row = $(this);
          let sample_id = current_row[0].cells[0].textContent;
          if (samples_to_highlight.includes(sample_id)) {
            current_row.removeClass("selected").toggleClass("selected");
          }
        });

      });

      function filter_sample_ids(sample_list) {
        // Extracts the sample_id value and removes any junk whitespace
        return sample_list.map(x => remove_whitespace(x['sample_id']))
      }

      function remove_whitespace(_string) {
        // Removes whitespace from a string
        return _string.replace(/<(?:.|\n)*?>/gm, '').replace(/\s/g, '');
      }

      function remove_from_id_list(deselected_samples) {
        // Provided with a list of samples, removes them from currently_selected_samples variable
        currently_selected_samples = currently_selected_samples.filter(item => !deselected_samples.includes(item));
        $("#sample_id_list").val(currently_selected_samples);
      }

    })

  </script>

{% endblock %}

miseq_portal/templates/sample_workbooks/sample_workbooks_index.html
{% extends "base.html" %}
{% load static i18n %}
{% block extra_css %}
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.jqueryui.min.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.dataTables.min.css">
{% endblock %}

{% block title %}Sample Workbooks{% endblock %}

{% block content %}

  <div class="page-header">
    <h1>My Workbooks
      <button type="button" class="btn btn-sm btn-light" data-toggle="modal"
              data-target="#selectionModal">
        <i class="fas fa-question-circle fa-lg"></i>
      </button>
    </h1>

    <!-- Analysis Sample Selection Modal -->
    <div class="modal fade" id="selectionModal" tabindex="-1" role="dialog" aria-labelledby="selectionModalLabel"
         aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="selectionModalLabel">Workbook Instructions</h5>
            <div class="modal-body">
              <ul>
                <li><strong>Workbooks</strong> provide an easy method for organizing and annotating groups of samples
                </li>
                <li>Click the <strong>Create</strong> button to start a new workbook</li>
                <li>Inside a workbook you can easily <strong>annotate</strong> individual samples with notes</li>
                <li>All of your workbooks are listed and easily accessible through this page</li>
                <li>Coming soon: apply analytical tools to contents of entire workbook</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="list-group">
    <a href="{% url 'sample_workbooks:create_new_workbook' %}"
       class="list-group-item list-group-item-action flex-column align-items-start list-group-item-success">
      <h4 class="mb-1"><i class="far fa-plus-square"></i> <strong>Create</strong> a new Workbook</h4>
    </a>
  </div>

  <br>

  <div id="workbooks">
    <div class="list-group">

      <table class="display compact table" style="width:100%">
        <thead>
        <tr>
          <th>Workbook Title</th>
          <th>Workbook Description</th>
          <th></th>
        </tr>
        </thead>
        {% for workbook in workbooks %}
          <tr>
            <td>
              <a href="{% url 'sample_workbooks:workbook_detail' pk=workbook.pk %}">
                <h5>{{ workbook.workbook_title }}</h5>
              </a>
            </td>
            <td>{{ workbook.workbook_description }}</td>
            <td>
              <a class="btn btn-danger btn-sm"
                 href={% url 'sample_workbooks:workbook_delete_view' pk=workbook.pk %}>Delete</a>
            </td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>
{% endblock %}

miseq_portal/templates/sample_workbooks/workbook_confirm_delete.html
{% extends "base.html" %}
{% load static i18n %}
{% block extra_css %}
{% endblock %}
{% block title %}Delete Workbook{% endblock %}

{% block content %}
  <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm"/>
  </form>
{% endblock %}

miseq_portal/templates/sample_workbooks/workbook_delete_success.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}Delete success{% endblock %}

{% block content %}

  <div class="alert alert-success" role="alert">
    <h3>Workbook successfully deleted</h3>
  </div>

{% endblock content %}