config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
                  path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
                  path(
                      "about/",
                      TemplateView.as_view(template_name="pages/about.html"),
                      name="about",
                  ),
                  # Django Admin, use {% url 'admin:index' %}
                  path(settings.ADMIN_URL, admin.site.urls),

                  # User management
                  path(
                      "users/",
                      include("miseq_portal.users.urls", namespace="users"),
                  ),
                  path("accounts/", include("allauth.urls")),

                  # Your stuff: custom urls includes go here
                  path("miseq_viewer/", include("miseq_portal.miseq_viewer.urls")),
                  path("miseq_uploader/", include("miseq_portal.miseq_uploader.urls")),
                  path("sample_search/", include("miseq_portal.sample_search.urls")),
                  path("analysis/", include("miseq_portal.analysis.urls")),
                  path("sample_merge/", include("miseq_portal.sample_merge.urls")),
                  path("sample_workbooks/", include("miseq_portal.sample_workbooks.urls")),
                  path("sample_downloader/", include("miseq_portal.sample_downloader.urls")),
                  path("minion_viewer/", include("miseq_portal.minion_viewer.urls")),
                  path("minion_uploader/", include("miseq_portal.minion_uploader.urls")),
              ] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

miseq_portal/analysis/urls.py
from django.urls import path, re_path

from miseq_portal.analysis.views import (
    tool_selection_view,
    my_jobs_view,
    job_submitted_view,
    analysis_group_detail_view,
    analysis_group_delete_view,
    analysis_group_delete_success_view,
    sample_select_view
)

app_name = "analysis"
urlpatterns = [
    # Sample selector
    path("sample_select/", view=sample_select_view, name="sample_select"),

    # Page for selecting analysis tools
    path("sample_select/tools/", view=tool_selection_view, name="tool_selection"),

    # Successful job submission page
    path("sample_select/tools/job_submitted/", view=job_submitted_view, name="job_submitted"),

    # Analysis jobs pages
    path("my_jobs/", view=my_jobs_view, name="my_jobs"),
    re_path("^my_jobs/(?P<pk>\d+)$", view=analysis_group_detail_view, name="analysis_group_detail_view"),
    re_path("^my_jobs/(?P<pk>\d+)/delete$", view=analysis_group_delete_view, name="analysis_group_delete_view"),

    # Analysis deleted success page
    path("analysis_group_deleted/success", view=analysis_group_delete_success_view,
         name="analysis_group_delete_success_view")
]

miseq_portal/core/urls.py
app_name = "core"

miseq_portal/users/urls.py
from django.urls import path

from miseq_portal.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

miseq_portal/analysis/forms.py
from django import forms
from .models import AnalysisGroup

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class AnalysisToolForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AnalysisToolForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-submitAnalysisJobForm'
        self.helper.form_class = 'blueForms'
        self.helper.form_method = 'post'
        self.helper.form_action = 'tool_selection'
        self.fields['job_type'].label = 'Job Type'
        self.helper.add_input(Submit('submit', 'Submit', css_class='btn btn-success'))

    class Meta:
        model = AnalysisGroup
        fields = ['job_type']
        widgets = {
            'job_type': forms.RadioSelect,
        }

miseq_portal/miseq_uploader/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.forms import Form


# MISEQ DIRECTORY
class UploadMiSeqDirectoryForm(Form):
    miseq_directory = forms.CharField(widget=forms.TextInput())

    def __init__(self, *args, **kwargs):
        super(UploadMiSeqDirectoryForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-uploadMiSeqDirectoryForm'
        self.helper.form_class = 'blueForms'
        self.helper.form_method = 'post'
        self.helper.form_action = 'upload_miseq_directory'
        self.fields['miseq_directory'].label = 'MiSeq Directory'
        self.helper.add_input(Submit('submit', 'Submit'))

miseq_portal/sample_downloader/forms.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render


class DownloadToolForm(forms.Form):
    file_choices = (
        ('Reads', 'Reads'),
        ('Assembly', 'Assembly'),
    )
    #   download_choice = forms.CharField(max_length=50, choices=file_choices, blank=False, default='Assembly')
    #    download_choice = forms.CharField(label='File Types', max_length=100)

# mutliple choice no submit button
#   download_choice = forms.MultipleChoiceField(
#        required=True,
#        widget=forms.CheckboxSelectMultiple,
#        choices=file_choices
#    )

  # drop down dox
  #  download_choice = forms.CharField(label='File Type to Download?', widget=forms.Select(choices=file_choices))


    download_choice = forms.ChoiceField(choices=file_choices, widget= forms.RadioSelect)


    def pick_file_type(request):
        submitted = False
        if request.method == "POST":
            form = DownloadToolForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                return HttpResponseRedirect('sample_downloader/receive/')
        return render(request, 'sample_downloader/receive/', {'form': form, 'submitted': submitted})

miseq_portal/analysis/views.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import View, TemplateView, DetailView, DeleteView

from miseq_portal.analysis.forms import AnalysisToolForm
from miseq_portal.analysis.models import AnalysisSample, AnalysisGroup, SendsketchResult, MobSuiteAnalysisPlasmid, \
    MobSuiteAnalysisGroup, RGIResult, RGIGroupResult, ConfindrGroupResult, ConfindrResult, rMLSTResult
from miseq_portal.analysis.tasks import submit_analysis_job
from miseq_portal.miseq_viewer.models import Sample, UserProjectRelationship

logger = logging.getLogger('django')


class SampleSelectView(LoginRequiredMixin, TemplateView):
    template_name = "analysis/sample_select.html"
    success_url = 'tools/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['approved_users'] = UserProjectRelationship.objects.filter(user_id=self.request.user)
        return context

    def post(self, request, *args, **kwargs):
        # Grab sample list from user selection from the analysis_index.html page via AJAX
        sample_id_list = request.POST.getlist('sample_id_list[]')

        # Get corresponding Sample objects from user selection
        sample_object_list = list()
        for sample_id in sample_id_list:
            sample_object = Sample.objects.get(sample_id=sample_id)
            sample_object_list.append(sample_object)

        # Create new AnalysisGroup
        analysis_group = AnalysisGroup(user=request.user)
        analysis_group.save()

        # Add objects to SampleAnalysisTemporaryGroup table
        for sample_object in sample_object_list:
            obj = AnalysisSample(sample_id=sample_object, user=request.user, group_id=analysis_group)
            obj.save()
        logger.info(f'Saved {sample_object_list} to {analysis_group} for user "{request.user}"')

        context = {'success': True,
                   'url': self.success_url}
        return JsonResponse(context)


sample_select_view = SampleSelectView.as_view()


class ToolSelectionView(LoginRequiredMixin, View):
    template_name = 'analysis/tool_selection.html'
    model = AnalysisGroup
    form_class = AnalysisToolForm
    success_url = 'job_submitted/'

    def get(self, request, *args, **kwargs):
        # Get the most recent Analysis Group belonging to user
        analysis_group = AnalysisGroup.objects.filter(user_id=self.request.user).order_by('-id')[0]
        analysis_samples = AnalysisSample.objects.filter(group_id=analysis_group)

        context = {
            'analysis_group': analysis_group,
            'analysis_samples': analysis_samples,
            'form': self.form_class
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            logger.info("Valid form")

            # Set job type for analysis_group
            analysis_group = AnalysisGroup.objects.filter(user_id=self.request.user).order_by('-id')[0]
            analysis_group.job_type = form.cleaned_data['job_type']
            analysis_group.save()
            logger.info(f"Queued job for {analysis_group}")

            # Submit analysis to queue. Note that the ID must be submitted because a straight object is not serializable
            submit_analysis_job.apply_async(args=[],
                                            kwargs={'analysis_group': analysis_group.id},
                                            queue='analysis_queue')
            return redirect(self.success_url)
        else:
            logger.error("Form is not valid")
            return render(request, self.template_name, {'form': form})


tool_selection_view = ToolSelectionView.as_view()


class MyJobsView(LoginRequiredMixin, View):
    template_name = 'analysis/my_jobs.html'

    def get(self, request):
        # Display samples only belonging only to the requesting user
        analysis_group = AnalysisGroup.objects.filter(user_id=self.request.user)
        context = {
            'analysis_group': analysis_group
        }
        return render(request, self.template_name, context)


my_jobs_view = MyJobsView.as_view()


class AnalysisGroupDetailView(LoginRequiredMixin, DetailView):
    model = AnalysisGroup
    context_object_name = 'analysis_group'
    template_name = "analysis/analysis_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['analysis_samples'] = AnalysisSample.objects.filter(group_id=context['analysis_group'])

        # Sendketch
        if context['analysis_group'].job_type == 'SendSketch':
            context['sendsketch_results'] = SendsketchResult.objects.filter(
                sample_id__analysissample__group_id=context['analysis_group']).order_by('-sample_id')

        # Mob Suite
        elif context['analysis_group'].job_type == 'MobRecon':

            # Add analysis samples to context
            context['mob_suite_analysis_samples'] = MobSuiteAnalysisGroup.objects.filter(
                analysis_sample__group_id=context['analysis_group']).order_by('-analysis_sample__sample_id')

            # Add plasmids to context
            context['mob_suite_analysis_plasmids'] = MobSuiteAnalysisPlasmid.objects.filter(
                group_id__analysis_sample__group_id=context['analysis_group']).order_by('-sample_id')

        # RGI
        elif context['analysis_group'].job_type == 'RGI':

            # RGI Result
            context['rgi_results'] = RGIResult.objects.filter(
                analysis_sample__group_id=context['analysis_group']).order_by('-analysis_sample__sample_id')

            # Group Result
            try:
                context['rgi_group_result'] = RGIGroupResult.objects.get(analysis_group=context['analysis_group'])
            except Exception as e:
                logger.info(f'Could not find group result for analysis; probably only executed on 1 sample')
                logger.info(e)
                context['rgi_group_result'] = None

        # Confindr
        elif context['analysis_group'].job_type == 'Confindr':
            context['confindr_group_result'] = ConfindrGroupResult.objects.get(analysis_group=context['analysis_group'])
            context['confindr_results'] = ConfindrResult.objects.filter(
                analysis_sample__group_id=context['analysis_group']).order_by('-analysis_sample__sample_id')
        # rMLST
        elif context['analysis_group'].job_type == 'rMLST':
            context['rmlst_results'] = rMLSTResult.objects.filter(
                analysis_sample__group_id=context['analysis_group']).order_by('-analysis_sample__sample_id')

        else:
            return context
        return context


analysis_group_detail_view = AnalysisGroupDetailView.as_view()


class JobSubmittedView(LoginRequiredMixin, TemplateView):
    template_name = 'analysis/job_submitted.html'


job_submitted_view = JobSubmittedView.as_view()


class AnalysisGroupDeleteView(LoginRequiredMixin, DeleteView):
    model = AnalysisGroup
    success_url = reverse_lazy('analysis:analysis_group_delete_success_view')


analysis_group_delete_view = AnalysisGroupDeleteView.as_view()


class AnalysisGroupDeleteSuccessView(LoginRequiredMixin, TemplateView):
    template_name = 'analysis/analysisgroup_delete_success.html'


analysis_group_delete_success_view = AnalysisGroupDeleteSuccessView.as_view()

miseq_portal/minion_viewer/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


# Create your views here.
class MinIONViewerIndexView(LoginRequiredMixin, TemplateView):
    template_name = 'minion_viewer/minion_viewer_index.html'

    def get_context_data(self, **kwargs):
        context = super(MinIONViewerIndexView, self).get_context_data(**kwargs)
        return context


minion_viewer_index_view = MinIONViewerIndexView.as_view()

miseq_portal/miseq_uploader/views.py
import logging
from pathlib import Path

from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views.generic import View, TemplateView

from miseq_portal.miseq_uploader.forms import UploadMiSeqDirectoryForm
from miseq_portal.miseq_uploader.upload_to_db import receive_miseq_run_dir

# logger = logging.getLogger('raven')
logger = logging.getLogger('django')


@method_decorator(staff_member_required, name='dispatch')
class MiseqUploaderView(LoginRequiredMixin, TemplateView):
    template_name = 'miseq_uploader/miseq_uploader.html'


miseq_uploader_view = MiseqUploaderView.as_view()


@method_decorator(staff_member_required, name='dispatch')
class SampleFormView(LoginRequiredMixin, View):
    template_name = 'miseq_uploader/sample_uploader.html'

    def get(self, request):
        return render(request, self.template_name, {})


sample_form_view = SampleFormView.as_view()


@method_decorator(staff_member_required, name='dispatch')
class MiSeqFormView(LoginRequiredMixin, UserPassesTestMixin, View):
    form_class = UploadMiSeqDirectoryForm
    template_name = 'miseq_uploader/upload_miseq_directory.html'

    # success_url = 'miseq_directory_uploaded/'  # TODO: actually make this page
    success_url = 'run_submitted/'

    # Only staff can access this page
    def test_func(self):
        if self.request.user.is_staff:
            return True
        else:
            raise Http404("You are not authenticated to view this page.")

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)

        if form.is_valid():
            receive_miseq_run_dir(Path(request.POST['miseq_directory']))
            return redirect(self.success_url)
        else:
            logging.warning("Could not submit form!")
            return render(request, self.template_name, {'form': form})


miseq_form_view = MiSeqFormView.as_view()


@method_decorator(staff_member_required, name='dispatch')
class RunSubmittedView(LoginRequiredMixin, TemplateView):
    template_name = 'miseq_uploader/run_submitted.html'


run_submitted_view = RunSubmittedView.as_view()

miseq_portal/templates/analysis/analysis_detail.html
{% extends "base.html" %}
{% load analysis_extras %}
{% load static i18n %}
{% block extra_css %}
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.jqueryui.min.css">
{% endblock %}
{% block title %}Analysis Detail{% endblock %}

{% block content %}

  <div class="page-header">

    <div class="row">
      <div class="col">
        <h1><strong>Group ID: </strong>{{ analysis_group.id }}</h1>
      </div>
      <div class="col">
        <h5><strong>User: </strong>{{ analysis_group.user }}</h5>
        <h5><strong>Job Type: </strong>{{ analysis_group.job_type }}</h5>
      </div>
    </div>

  </div>

  <hr>

  {% if analysis_group.job_type == "SendSketch" %}
    <div id="sendsketch-results">
      {% include "analysis/results/sendsketch_results.html" %}
    </div>
  {% elif analysis_group.job_type == "MobRecon" %}
    <div id="mob_recon-results">
      {% include "analysis/results/mob_recon_results.html" %}
    </div>
  {% elif analysis_group.job_type == "RGI" %}
    <div id="mob_recon-results">
      {% include "analysis/results/rgi_results.html" %}
    </div>
  {% elif analysis_group.job_type == "Confindr" %}
    <div id="confindr-results">
      {% include "analysis/results/confindr_results.html" %}
    </div>
  {% elif analysis_group.job_type == "rMLST" %}
    <div id="rmlst-results">
      {% include "analysis/results/rmlst_results.html" %}
    </div>
  {% endif %}

  <hr>

  {#  Delete analysis#}
  <div>
    <a class="btn btn-outline-danger"
       href="{% url 'analysis:analysis_group_delete_view' pk=analysis_group.pk %}"
       role="button"><i class="fas fa-trash"></i> Delete Analysis
    </a>
  </div>
  <br>


{% endblock content %}

{% block extra_javascript %}
  <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/dataTables.jqueryui.min.js"></script>

  <script>
    $.ajaxSetup({
      headers: {"X-CSRFToken": '{{csrf_token}}'}
    });

    $(document).ready(function () {
      let table = $('.analysis_table').DataTable({
        dom: 'Bfrtip',
        pageLength: 10,
        scrollX: true,
        paging: false,
        searching: false,
        info: false
      })
    });

  </script>
{% endblock %}

miseq_portal/templates/analysis/analysisgroup_confirm_delete.html
{% extends "base.html" %}
{% load static i18n %}
{% block extra_css %}
{% endblock %}
{% block title %}Delete Analysis{% endblock %}
{% block content %}
  <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm"/>
  </form>
{% endblock %}

miseq_portal/templates/analysis/analysisgroup_delete_success.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Delete success{% endblock %}
{% block content %}
  <div class="alert alert-success" role="alert">
    <h3>Analysis Group successfully deleted</h3>
  </div>
{% endblock content %}

miseq_portal/templates/analysis/job_submitted.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}Job Submitted{% endblock %}

{% block content %}

  <div class="alert alert-success" role="alert">
    <h3>Job submitted successfully</h3>
    <h5>Visit the <a href="{% url 'analysis:my_jobs' %}">My Jobs</a> page to view its progress.</h5>
  </div>

{% endblock content %}

miseq_portal/templates/analysis/my_jobs.html
{% extends "base.html" %}
{% load static i18n %}
{% block extra_css %}
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.jqueryui.min.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.dataTables.min.css">
{% endblock %}

{% block title %}My Jobs{% endblock %}

{% block content %}

  <div class="page-header">
    <h1>My Jobs</h1>
  </div>

  <table id="job_table" class="display compact">
    <thead>
    <tr>
      <th>Job ID</th>
      <th>Job Type</th>
      <th>Status</th>
      <th>Results</th>
      {# TODO: Fix the date sorting for this - use the DD/MM/YYYY format. See run page html for example #}
     <th>Date Submitted</th>
    </tr>
    </thead>
    <tbody>
    {% for group in analysis_group %}
      <tr>
        <td>{{ group.id }}</td>
        <td>{{ group.job_type }}</td>
        {% if group.job_status == "Complete" %}
          <td>
            <div class="progress">
              <div class="progress-bar bg-success" role="progressbar" style="width: 100%">
                Complete
              </div>
            </div>
          </td>
        {% elif group.job_status == "Queued" %}
          <td>
            <div class="progress">
              <div class="progress-bar bg-warning" role="progressbar" style="width: 100%">
                Queued
              </div>
            </div>
          </td>
        {% elif group.job_status == "Working" %}
          <td>
            <div class="progress">
              <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar"
                   style="width: 100%">
                Working
              </div>
            </div>
          </td>
        {% elif group.job_status == "Failed" %}
          <td>
            <div class="progress">
              <div class="progress-bar bg-danger" role="progressbar" style="width: 100%">
                Failed
              </div>
            </div>
          </td>
        {% endif %}
        {% if group.job_status == "Complete" %}
          <td>
            <a href="{% url 'analysis:analysis_group_detail_view' pk=group.pk %}">Results</a>
          </td>
        {% else %}
          <td>N/A</td>
        {% endif %}
        <td>{{ group.created }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  <br>
{% endblock content %}

{% block extra_javascript %}
  <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/dataTables.jqueryui.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>

  <script>
    $.ajaxSetup({
      headers: {"X-CSRFToken": '{{csrf_token}}'}
    });

    $(document).ready(function () {
      let table = $('#job_table').DataTable({
        pageLength: 20,
        order: [[0, "desc"]]
      })
    });

  </script>
{% endblock %}

miseq_portal/templates/analysis/tool_descriptions.html
<div class="collapse" id="toolDescriptions">
  <div class="card">
    <div class="card-header">
      A number of tools are available to process existing datasets:
    </div>
    <ol class="list-group list-group-flush">
      <li class="list-group-item"><h5>Sendsketch</h5>
        <p class="card-text">Sendsketch compares query sketches to reference sketches hosted on a remote server via
          the Internet.
          Uses the R1 and R2 reads of any given sample and compares against a sketch of RefSeq.</p>
      </li>
      <li class="list-group-item"><h5>Mob Recon</h5>
        <p class="card-text">This tool reconstructs individual plasmid sequences from draft genome assemblies using
          the clustered plasmid reference
          databases provided by MOB-cluster. Provides in silico predictions of the replicon family, relaxase type,
          mate-pair
          formation type and predicted transferability of the plasmid.</p>
      </li>
      <li class="list-group-item"><h5>RGI</h5>
        <p class="card-text">This application is used to predict resistome(s) from protein or nucleotide data based on
          homology and SNP models. The
          application uses reference data from the Comprehensive Antibiotic Resistance Database (CARD).</p>
      </li>
      <li class="list-group-item"><h5>ConFindr</h5>
        <p class="card-text">ConFindr works by looking at conserved core genes - either using rMLST genes (53 genes are
          known to be single copy and
          conserved across all bacteria with some known exceptions, which ConFindr handles), or custom sets of genes
          derived
          from core-genome schemes. As the genes ConFindr looks at are single copy, any sample that has multiple alleles
          of one
          or more gene is likely to be contaminated.</p>
      </li>
      <li class="list-group-item"><h5>PlasmidAMR <span
        class="font-weight-light text-secondary">(under construction)</span></h5>
        <p class="card-text">This tool will first extract plasmids from your sample with Mob Recon, then conduct
          resitome prediction via RGI on any detected plasmids.</p>
      </li>
      <li class="list-group-item"><h5>Core Pipeline <span
        class="font-weight-light text-secondary">(under construction)</span></h5>
        <p class="card-text">This tool will establish a core genome among the selected samples,
          construct a core tree, generate a network visualization, and more.
          Supports a maximum of 100 samples; if you need a larger sample set, please contact the administrator.</p>
      </li>
    </ol>
  </div>
</div>

miseq_portal/templates/analysis/tool_selection.html
{% extends "base.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}
{% block extra_css %}
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.jqueryui.min.css">
{% endblock %}

{% block title %}Analysis{% endblock %}

{% block content %}

  <div class="page-header">
    <h1>Analysis Suite</h1>
  </div>

  <div class="card mb-3">
    <div class="card-header"><h4>Analysis Group</h4></div>
    <div class="card-body text-success">
      {% for sample_object in analysis_samples %}
        <p class="card-text">{{ sample_object.sample_id }}</p>
      {% endfor %}
    </div>
  </div>
  <br>

  <div class="card mb-3">
    <div class="card-header"><h4>Tool Selection</h4>Select a tool to apply to the Sample Group</div>

    <div class="card-body">
      <form action="{% url "analysis:tool_selection" %}" method="post" enctype="multipart/form-data">
        {% crispy form %}
      </form>
    </div>

  </div>

  {#  TODO: Implement this#}
  {#  <div class="card mb-3">#}
  {#    <div class="card-header"><h4>Comments (not yet functional)</h4>Provide a description of the sample group or analysis#}
  {#    </div>#}
  {##}
  {#    <div class="card-body">#}
  {#      <form action="{% url "analysis:tool_selection" %}" method="post" enctype="multipart/form-data">#}
  {#        {% crispy form %}#}
  {#      </form>#}
  {#    </div>#}
  {#  </div>#}

  <br>

{% endblock content %}

{% block extra_javascript %}
  <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/dataTables.jqueryui.min.js"></script>
{% endblock %}