config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
                  path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
                  path(
                      "about/",
                      TemplateView.as_view(template_name="pages/about.html"),
                      name="about",
                  ),
                  # Django Admin, use {% url 'admin:index' %}
                  path(settings.ADMIN_URL, admin.site.urls),

                  # User management
                  path(
                      "users/",
                      include("miseq_portal.users.urls", namespace="users"),
                  ),
                  path("accounts/", include("allauth.urls")),

                  # Your stuff: custom urls includes go here
                  path("miseq_viewer/", include("miseq_portal.miseq_viewer.urls")),
                  path("miseq_uploader/", include("miseq_portal.miseq_uploader.urls")),
                  path("sample_search/", include("miseq_portal.sample_search.urls")),
                  path("analysis/", include("miseq_portal.analysis.urls")),
                  path("sample_merge/", include("miseq_portal.sample_merge.urls")),
                  path("sample_workbooks/", include("miseq_portal.sample_workbooks.urls")),
                  path("sample_downloader/", include("miseq_portal.sample_downloader.urls")),
                  path("minion_viewer/", include("miseq_portal.minion_viewer.urls")),
                  path("minion_uploader/", include("miseq_portal.minion_uploader.urls")),
              ] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

miseq_portal/analysis/urls.py
from django.urls import path, re_path

from miseq_portal.analysis.views import (
    tool_selection_view,
    my_jobs_view,
    job_submitted_view,
    analysis_group_detail_view,
    analysis_group_delete_view,
    analysis_group_delete_success_view,
    sample_select_view
)

app_name = "analysis"
urlpatterns = [
    # Sample selector
    path("sample_select/", view=sample_select_view, name="sample_select"),

    # Page for selecting analysis tools
    path("sample_select/tools/", view=tool_selection_view, name="tool_selection"),

    # Successful job submission page
    path("sample_select/tools/job_submitted/", view=job_submitted_view, name="job_submitted"),

    # Analysis jobs pages
    path("my_jobs/", view=my_jobs_view, name="my_jobs"),
    re_path("^my_jobs/(?P<pk>\d+)$", view=analysis_group_detail_view, name="analysis_group_detail_view"),
    re_path("^my_jobs/(?P<pk>\d+)/delete$", view=analysis_group_delete_view, name="analysis_group_delete_view"),

    # Analysis deleted success page
    path("analysis_group_deleted/success", view=analysis_group_delete_success_view,
         name="analysis_group_delete_success_view")
]

miseq_portal/core/urls.py
app_name = "core"

miseq_portal/minion_viewer/urls.py
from django.urls import path, re_path, include
from rest_framework import routers

from miseq_portal.minion_viewer.views import (
    minion_viewer_index_view,
    minion_run_list_view,
    minion_sample_detail_view,
    minion_run_detail_view,
    MinIONRunViewSet,
    MinIONRunSamplesheetViewSet,
    MinIONSampleViewSet,
)

app_name = "minion_viewer"

# Django-rest-framework (https://django-rest-framework-datatables.readthedocs.io/en/latest/tutorial.html)
router = routers.DefaultRouter()
router.register(r'minion_runs', MinIONRunViewSet, basename='minion-run')
router.register(r'minion_samples', MinIONSampleViewSet, basename='minion-sample')
router.register(r'minion_samplesheets', MinIONRunSamplesheetViewSet, basename='minion-samplesheet')

urlpatterns = [
    path("", view=minion_viewer_index_view, name="minion_viewer_index"),
    re_path("^api/", include(router.urls), name="minion_viewer_api"),
    path("runs/", view=minion_run_list_view, name="minion_viewer_runs"),
    re_path("^run/(?P<pk>\d+)$", view=minion_run_detail_view, name="minion_run_detail"),
    re_path("^sample/(?P<pk>\d+)$", view=minion_sample_detail_view,
            name="minion_sample_detail")
]

miseq_portal/miseq_viewer/urls.py
from django.urls import path, re_path, include
from rest_framework import routers

from miseq_portal.miseq_viewer.views import (
    project_list_view,
    project_detail_view,
    run_list_view,
    run_detail_view,
    sample_detail_view,
    qaqc_excel,
    SampleViewSet, RunViewSet, ProjectViewSet
    # samples_api_view
)

app_name = "miseq_viewer"

# Django-rest-framework (https://django-rest-framework-datatables.readthedocs.io/en/latest/tutorial.html)
router = routers.DefaultRouter()
router.register(r'samples', SampleViewSet, basename='samples-detail')
router.register(r'runs', RunViewSet, basename='runs-detail')
router.register(r'projects', ProjectViewSet, basename='projects-detail')

urlpatterns = [
    path("projects/", view=project_list_view, name="miseq_viewer_projects"),
    path("runs/", view=run_list_view, name="miseq_viewer_runs"),
    path('qaqcexcel/', view=qaqc_excel, name='miseq_viewer_qaqc_excel'),
    # path("samples_api/", view=samples_api_view, name="miseq_viewer_samples_api"),
    re_path("^api/", include(router.urls), name="miseq_viewer_api"),
    re_path("^project/(?P<pk>\d+)$", view=project_detail_view, name="miseq_viewer_project_detail"),
    re_path("^run/(?P<pk>\d+)$", view=run_detail_view, name="miseq_viewer_run_detail"),
    re_path("^sample/(?P<pk>\d+)$", view=sample_detail_view,
            name="miseq_viewer_sample_detail")
]

miseq_portal/sample_merge/urls.py
from django.urls import path, re_path

from miseq_portal.sample_merge.views import (
    sample_merge_index_view,
    sample_merge_queue_view,
    merge_success_view,
    sample_delete_view,
    sample_delete_success_view
)

app_name = "sample_merge"
urlpatterns = [
    # Index
    path("manual/", view=sample_merge_index_view, name="sample_merge_index"),
    path("queue/", view=sample_merge_queue_view, name="sample_merge_queue"),
    path("sample_delete/success", view=sample_delete_success_view, name="sample_delete_success_view"),
    re_path("^delete/(?P<pk>\d+)$", view=sample_delete_view, name="sample_delete_view"),
    re_path("^manual/merge_success/", view=merge_success_view, name="merge_success_view")
]

miseq_portal/sample_search/urls.py
from django.urls import path, re_path

from miseq_portal.sample_search.views import (
    sample_search_view,
    sample_search_view_json
)

app_name = "sample_search"
urlpatterns = [
    path("", view=sample_search_view, name="sample_search"),
    re_path("^sample_search_view_json", view=sample_search_view_json, name="sample_search_view_json"),
]

miseq_portal/users/urls.py
from django.urls import path

from miseq_portal.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

miseq_portal/analysis/forms.py
from django import forms
from .models import AnalysisGroup

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class AnalysisToolForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AnalysisToolForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-submitAnalysisJobForm'
        self.helper.form_class = 'blueForms'
        self.helper.form_method = 'post'
        self.helper.form_action = 'tool_selection'
        self.fields['job_type'].label = 'Job Type'
        self.helper.add_input(Submit('submit', 'Submit', css_class='btn btn-success'))

    class Meta:
        model = AnalysisGroup
        fields = ['job_type']
        widgets = {
            'job_type': forms.RadioSelect,
        }

miseq_portal/miseq_uploader/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.forms import Form


# MISEQ DIRECTORY
class UploadMiSeqDirectoryForm(Form):
    miseq_directory = forms.CharField(widget=forms.TextInput())

    def __init__(self, *args, **kwargs):
        super(UploadMiSeqDirectoryForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-uploadMiSeqDirectoryForm'
        self.helper.form_class = 'blueForms'
        self.helper.form_method = 'post'
        self.helper.form_action = 'upload_miseq_directory'
        self.fields['miseq_directory'].label = 'MiSeq Directory'
        self.helper.add_input(Submit('submit', 'Submit'))

miseq_portal/analysis/views.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import View, TemplateView, DetailView, DeleteView

from miseq_portal.analysis.forms import AnalysisToolForm
from miseq_portal.analysis.models import AnalysisSample, AnalysisGroup, SendsketchResult, MobSuiteAnalysisPlasmid, \
    MobSuiteAnalysisGroup, RGIResult, RGIGroupResult, ConfindrGroupResult, ConfindrResult, rMLSTResult
from miseq_portal.analysis.tasks import submit_analysis_job
from miseq_portal.miseq_viewer.models import Sample, UserProjectRelationship

logger = logging.getLogger('django')


class SampleSelectView(LoginRequiredMixin, TemplateView):
    template_name = "analysis/sample_select.html"
    success_url = 'tools/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['approved_users'] = UserProjectRelationship.objects.filter(user_id=self.request.user)
        return context

    def post(self, request, *args, **kwargs):
        # Grab sample list from user selection from the analysis_index.html page via AJAX
        sample_id_list = request.POST.getlist('sample_id_list[]')

        # Get corresponding Sample objects from user selection
        sample_object_list = list()
        for sample_id in sample_id_list:
            sample_object = Sample.objects.get(sample_id=sample_id)
            sample_object_list.append(sample_object)

        # Create new AnalysisGroup
        analysis_group = AnalysisGroup(user=request.user)
        analysis_group.save()

        # Add objects to SampleAnalysisTemporaryGroup table
        for sample_object in sample_object_list:
            obj = AnalysisSample(sample_id=sample_object, user=request.user, group_id=analysis_group)
            obj.save()
        logger.info(f'Saved {sample_object_list} to {analysis_group} for user "{request.user}"')

        context = {'success': True,
                   'url': self.success_url}
        return JsonResponse(context)


sample_select_view = SampleSelectView.as_view()


class ToolSelectionView(LoginRequiredMixin, View):
    template_name = 'analysis/tool_selection.html'
    model = AnalysisGroup
    form_class = AnalysisToolForm
    success_url = 'job_submitted/'

    def get(self, request, *args, **kwargs):
        # Get the most recent Analysis Group belonging to user
        analysis_group = AnalysisGroup.objects.filter(user_id=self.request.user).order_by('-id')[0]
        analysis_samples = AnalysisSample.objects.filter(group_id=analysis_group)

        context = {
            'analysis_group': analysis_group,
            'analysis_samples': analysis_samples,
            'form': self.form_class
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            logger.info("Valid form")

            # Set job type for analysis_group
            analysis_group = AnalysisGroup.objects.filter(user_id=self.request.user).order_by('-id')[0]
            analysis_group.job_type = form.cleaned_data['job_type']
            analysis_group.save()
            logger.info(f"Queued job for {analysis_group}")

            # Submit analysis to queue. Note that the ID must be submitted because a straight object is not serializable
            submit_analysis_job.apply_async(args=[],
                                            kwargs={'analysis_group': analysis_group.id},
                                            queue='analysis_queue')
            return redirect(self.success_url)
        else:
            logger.error("Form is not valid")
            return render(request, self.template_name, {'form': form})


tool_selection_view = ToolSelectionView.as_view()


class MyJobsView(LoginRequiredMixin, View):
    template_name = 'analysis/my_jobs.html'

    def get(self, request):
        # Display samples only belonging only to the requesting user
        analysis_group = AnalysisGroup.objects.filter(user_id=self.request.user)
        context = {
            'analysis_group': analysis_group
        }
        return render(request, self.template_name, context)


my_jobs_view = MyJobsView.as_view()


class AnalysisGroupDetailView(LoginRequiredMixin, DetailView):
    model = AnalysisGroup
    context_object_name = 'analysis_group'
    template_name = "analysis/analysis_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['analysis_samples'] = AnalysisSample.objects.filter(group_id=context['analysis_group'])

        # Sendketch
        if context['analysis_group'].job_type == 'SendSketch':
            context['sendsketch_results'] = SendsketchResult.objects.filter(
                sample_id__analysissample__group_id=context['analysis_group']).order_by('-sample_id')

        # Mob Suite
        elif context['analysis_group'].job_type == 'MobRecon':

            # Add analysis samples to context
            context['mob_suite_analysis_samples'] = MobSuiteAnalysisGroup.objects.filter(
                analysis_sample__group_id=context['analysis_group']).order_by('-analysis_sample__sample_id')

            # Add plasmids to context
            context['mob_suite_analysis_plasmids'] = MobSuiteAnalysisPlasmid.objects.filter(
                group_id__analysis_sample__group_id=context['analysis_group']).order_by('-sample_id')

        # RGI
        elif context['analysis_group'].job_type == 'RGI':

            # RGI Result
            context['rgi_results'] = RGIResult.objects.filter(
                analysis_sample__group_id=context['analysis_group']).order_by('-analysis_sample__sample_id')

            # Group Result
            try:
                context['rgi_group_result'] = RGIGroupResult.objects.get(analysis_group=context['analysis_group'])
            except Exception as e:
                logger.info(f'Could not find group result for analysis; probably only executed on 1 sample')
                logger.info(e)
                context['rgi_group_result'] = None

        # Confindr
        elif context['analysis_group'].job_type == 'Confindr':
            context['confindr_group_result'] = ConfindrGroupResult.objects.get(analysis_group=context['analysis_group'])
            context['confindr_results'] = ConfindrResult.objects.filter(
                analysis_sample__group_id=context['analysis_group']).order_by('-analysis_sample__sample_id')
        # rMLST
        elif context['analysis_group'].job_type == 'rMLST':
            context['rmlst_results'] = rMLSTResult.objects.filter(
                analysis_sample__group_id=context['analysis_group']).order_by('-analysis_sample__sample_id')

        else:
            return context
        return context


analysis_group_detail_view = AnalysisGroupDetailView.as_view()


class JobSubmittedView(LoginRequiredMixin, TemplateView):
    template_name = 'analysis/job_submitted.html'


job_submitted_view = JobSubmittedView.as_view()


class AnalysisGroupDeleteView(LoginRequiredMixin, DeleteView):
    model = AnalysisGroup
    success_url = reverse_lazy('analysis:analysis_group_delete_success_view')


analysis_group_delete_view = AnalysisGroupDeleteView.as_view()


class AnalysisGroupDeleteSuccessView(LoginRequiredMixin, TemplateView):
    template_name = 'analysis/analysisgroup_delete_success.html'


analysis_group_delete_success_view = AnalysisGroupDeleteSuccessView.as_view()

miseq_portal/minion_viewer/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


# Create your views here.
class MinIONViewerIndexView(LoginRequiredMixin, TemplateView):
    template_name = 'minion_viewer/minion_viewer_index.html'

    def get_context_data(self, **kwargs):
        context = super(MinIONViewerIndexView, self).get_context_data(**kwargs)
        return context


minion_viewer_index_view = MinIONViewerIndexView.as_view()

miseq_portal/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

miseq_portal/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}Genomics Portal{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0 shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Forest Dussault">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
  <![endif]-->

  <link rel="icon" type="image/png" href="{% static 'favicon.png' %}">

  {% block css %}

    <!-- Latest compiled and minified Bootstrap 4.1.1 CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    {# Dashboard styling #}
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">

  {% endblock %}
  {% block extra_css %}
  {% endblock %}

</head>

<body>
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0" id="portal-navbar">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'home' %}" id="portal-brand">
    <i class="fas fa-dna"></i>
    <span class="text">Genomics Portal</span>
  </a>
  {% if request.user.is_authenticated %}
    {# SEARCH BAR #}
    <form action="{% url 'sample_search:sample_search' %}" method="get" style='width:100%;'>
      <input class="form-control form-control-lg w-100" type="text" placeholder="Sample Search"
             aria-label="Search" name="search_term" id="search_bar">
    </form>
    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <a class="nav-link "
           href="{% url 'users:detail' request.user.username %}"><i class="fas fa-user"></i> Profile
          ({{ request.user.username }})</a>
      </li>
    </ul>
    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <a class="nav-link " href="{% url 'account_logout' %}"><i class="fas fa-sign-out-alt"></i> Sign Out</a>
      </li>
    </ul>
  {% else %}
    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <a id="log-in-link" class="nav-link "
           href="{% url 'account_login' %}"><i class="fas fa-sign-in-alt"></i> Sign In</a>
      </li>
    </ul>
  {% endif %}
  {% if request.user.is_superuser %}
    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <a class="btn btn-outline-warning" href="{% url 'admin:index' %}"><span> Admin Panel </span></a>
      </li>
    </ul>
  {% endif %}
</nav>

<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}"><i class="fas fa-home"></i>
              Home <span class="sr-only">(current)</span></a>
          </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link "
                 href="{% url 'miseq_viewer:miseq_viewer_projects' %}"><i class="fas fa-project-diagram"></i>
                Projects</a>
            </li>
            {% if request.user.is_staff %}
              <li class="nav-item">
                <a class="nav-link "
                   href="{% url 'miseq_viewer:miseq_viewer_runs' %}">
                  <span class="icon-miseq"></span>
                  MiSeq Runs</a>
              </li>
              <li class="nav-item">
                <a class="nav-link "
                   href="{% url 'minion_viewer:minion_viewer_runs' %}">
                  <span class="icon-miseq"></span>
                  MinION Runs</a>
              </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link "
                 href="{% url 'analysis:sample_select' %}"><i class="fas fa-flask"></i> Analysis</a>
            </li>
            {% if request.user.is_staff %}
{#              <li class="nav-item">#}
{#                <a class="nav-link "#}
{#                   href="{% url 'sample_merge:sample_merge_queue' %}"><i class="fas fa-clone"></i> Merge Queue</a>#}
{#              </li>#}
              <li class="nav-item">
                <a class="nav-link "
                   href="{% url 'sample_merge:sample_merge_index' %}"><i class="fas fa-plus-square"></i> Manual
                  Merge</a>
              </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link "
                 href="{% url 'analysis:my_jobs' %}"><i class="fas fa-tasks"></i> My Jobs</a>
            </li>
            <li class="nav-item">
              <a class="nav-link "
                 href="{% url 'sample_workbooks:sample_workbook_index' %}"><i class="fas fa-book"></i> Workbooks</a>
            </li>
          {% endif %}
          {% if request.user.is_staff %}
            <div class="alert alert-danger" role="alert">
              <li class="nav-item">
                <span class="badge badge-danger">Admin only</span>
              </li>
              <li class="nav-item">
                <a class="nav-link "
                   href="{% url 'miseq_uploader:miseq_uploader' %}"><i class="fas fa-upload"></i> MiSeq Uploader </a>
              </li>
              <li class="nav-item">
                <a class="nav-link "
                   href="{% url 'minion_uploader:minion_uploader_index' %}"><i class="fas fa-upload"></i> MinION
                  Uploader </a>
              </li>
            </div>
            <hr>
          {% endif %}
        </ul>
      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
      <div class="container">
        {% if messages %}
          {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
        {% endif %}
      </div>
      {% block content %}
      {% endblock content %}
      <br>
    </main>
  </div>
</div>
<br>

{% block modal %}{% endblock modal %}

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{% block javascript %}

  <!-- Required by Bootstrap v4.1.1 -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
          integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
          integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
          crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
          integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
          crossorigin="anonymous"></script>

  <!-- Your stuff: Third-party javascript libraries go here -->

  <!-- place project specific Javascript in this file -->

  <script src="{% static 'js/project.js' %}"></script>

{% endblock javascript %}
{% block extra_javascript %}
{% endblock %}
</body>
</html>